"""
report_files.py

Turns Ava's plain text assistant report into downloadable PDF and Word
(.docx) files, in addition to the plain text download already offered.
Both files carry a small credit line at the bottom, and can optionally
include a chart image (for example the financial snapshot chart) placed
just below the title.
"""

import io
import html
from datetime import datetime

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Image as PdfImage, Spacer

from docx import Document
from docx.shared import Pt, RGBColor, Inches

CREDIT_LINE = "Built by Khan Zaid - khanzack355@gmail.com"


def _split_blocks(report_text: str) -> list[str]:
    return [block.strip() for block in report_text.strip().split("\n\n") if block.strip()]


def _is_heading(block: str) -> bool:
    return "\n" not in block and block.endswith(":") and len(block) < 80


def build_pdf_bytes(report_text: str, title: str, chart_image_bytes: bytes | None = None) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "AvaTitle", parent=styles["Title"], fontName="Helvetica-Bold",
        fontSize=20, spaceAfter=4,
    )
    meta_style = ParagraphStyle(
        "AvaMeta", parent=styles["Normal"], textColor=colors.HexColor("#5B6B74"),
        fontSize=9, spaceAfter=18,
    )
    heading_style = ParagraphStyle(
        "AvaHeading", parent=styles["Heading2"], fontName="Helvetica-Bold",
        fontSize=12, textColor=colors.HexColor("#1C2B33"), spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "AvaBody", parent=styles["Normal"], fontSize=10.5, leading=15, spaceAfter=8,
    )
    footer_style = ParagraphStyle(
        "AvaFooter", parent=styles["Normal"], fontSize=8,
        textColor=colors.HexColor("#5B6B74"), spaceBefore=24,
    )

    story = [
        Paragraph(html.escape(title), title_style),
        Paragraph(
            html.escape(f"Generated by Ava on {datetime.now().strftime('%B %d, %Y')}"),
            meta_style,
        ),
    ]

    if chart_image_bytes:
        chart_buffer = io.BytesIO(chart_image_bytes)
        story.append(PdfImage(chart_buffer, width=5.0 * inch, height=2.9 * inch))
        story.append(Spacer(1, 10))

    for block in _split_blocks(report_text):
        if _is_heading(block):
            story.append(Paragraph(html.escape(block.rstrip(":")), heading_style))
        else:
            safe = html.escape(block).replace("\n", "<br/>")
            story.append(Paragraph(safe, body_style))

    story.append(Paragraph(html.escape(CREDIT_LINE), footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def build_docx_bytes(report_text: str, title: str, chart_image_bytes: bytes | None = None) -> bytes:
    document = Document()

    document.add_heading(title, level=1)
    meta = document.add_paragraph(f"Generated by Ava on {datetime.now().strftime('%B %d, %Y')}")
    meta.runs[0].font.size = Pt(9)
    meta.runs[0].font.color.rgb = RGBColor(0x5B, 0x6B, 0x74)

    if chart_image_bytes:
        chart_buffer = io.BytesIO(chart_image_bytes)
        document.add_picture(chart_buffer, width=Inches(5.0))

    for block in _split_blocks(report_text):
        if _is_heading(block):
            document.add_heading(block.rstrip(":"), level=2)
        else:
            for line in block.split("\n"):
                document.add_paragraph(line)

    document.add_paragraph()
    footer = document.add_paragraph(CREDIT_LINE)
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x5B, 0x6B, 0x74)

    buffer = io.BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return buffer.read()
